### ISSUE TITLE
Fix body parsing in api.js

### ISSUE THREAD

**Issue by AlgorithmicEntropy** [DavidRisch/kicker#14]
Parsing the received json correctly is required to handle post requests

**Comment by DavidRisch** [comment]
What `received json` are you refering to?

**Comment by AlgorithmicEntropy** [comment]
Refering to the body to the received post request.
Without the body parser module, no specified properties can be read from the request body when posting to the api with js

**Comment by DavidRisch** [comment]
Closed by #16
