### ISSUE TITLE
Fix duplicate user registration

### ISSUE THREAD

**Issue by AlgorithmicEntropy** [DavidRisch/kicker#32]
Users can register multiple times with the same username

**Comment by DavidRisch** [comment]
This issue seems to match `task 2.4`.
That task is assigned to @Julian-Krtz 
@Julian-Krtz , @SebastianWallat : please agree on what should happen with this issue (and its pr)

**Comment by AlgorithmicEntropy** [comment]
I completly missed the existence of task 2.4 ...
@Julian-Krtz how much progress did you already make on this task ?

**Comment by DavidRisch** [comment]
@SebastianWallat: since @Julian-Krtz has not replied in 14 days you may assign the task to yourself and mark your pr as ready.
