### ISSUE TITLE
Problematic playernumbers in tournament creation

### ISSUE THREAD

**Issue by AlgorithmicEntropy** [DavidRisch/kicker#95]
`src/tournament` implements functionality to create all matches for 2v2 and 1v1 deathmatch tournaments.
The code will not return correct results  if the playernumber validates following constraints:

- number of players % 4 == 0 (2v2 match mode)

-  number of players % 2 == 0 (1v1 match mode)

These and other edge cases (0 players, ...) need proper error handling (client and server)

**Comment by DavidRisch** [comment]
Closing because this project has ended.
